### ISSUE TITLE
ON/OFF switch pin 5-6 in default iamge

### ISSUE THREAD

**Issue by dudman** [seeul8er/DroneBridge#22]
I'm new to rpi... but would it make sense to make something like https://howchoo.com/g/mwnlytk3zmm/how-to-add-a-power-button-to-your-raspberry-pi which is 2 scripts, a standard feature of the rpi images ? 

That way shutdown, startup with a button or just shorting out the pins is easier. Perhaps people do it in a different way that I've missed.

**Comment by seeul8er** [comment]
I just unplug the Pis :)

This is a very specific setup. If people want this they can simply add it to their image. I am not planning on adding it by default. 
I have got a plugin system planned. With that people will be able to easily add their own scripts to the startup procedure.
