### ISSUE TITLE
new relase?

### ISSUE THREAD

**Issue by naughtyxp** [seeul8er/DroneBridge#39]
hi,

When will the new version relase?
Will it support new  intel cards?

**Comment by seeul8er** [comment]
I am currently packed with lots of other stuff. I could think of a new release somewhere around August. I got a lot of changes coming. Some of them are already working, others need fixing/testing.

Support for new cards is very hard. I do not know about any worthy (high power, good drivers) Intel cards. So no. No support for new Intel cards.
