### ISSUE TITLE
Discontinue iNav support

### ISSUE THREAD

**Issue by seeul8er** [seeul8er/DroneBridge#41]
Supporting iNav & MAVLink is very time consuming for a single developer and makes the system more complicated since iNav "needs" two serial ports (MSP & LTM)

Looks like Ardupilot now supports cheaper hardware, so the big advantage of iNav over price seems to be gone now. Does it make any sense to keep supporting iNav? Ardupilot looks like the go-to option for me:

- Better library support, SITL Simulator
- Better documentation
- More features
- Bigger community

**Comment by mickey2011** [comment]
But the Ardupilot GUI is a mess. The INAV GUI is a lot cleaner these days

**Comment by TGithubbr** [comment]
I think iNav is pretty irrelevant these days. Maybe make it like a module and try to carry it on to newer versions and don't implement features for it which would require changes to the core iNav communication. Or maybe someone in the community could do it?
