### ISSUE TITLE
Add support for iPhone users

### ISSUE THREAD

**Issue by STiXzoOR** [seeul8er/DroneBridge#8]
hey you have done a great job with this and i'm looking forward to use it in the future. Is there going to be any support for iPhone users? thanks.

**Comment by seeul8er** [comment]
As much as I'd love to see an iOS app it is just not manageable. Just to name a few things:

- too much work building a second app (android is Java while iOS is C++)
- maintaining two apps plus the DroneBridge images is too much work for a single person
- You need to have a Mac to be able to develop iOS apps (I do not plan on ever buying one :smile: )
- An Apple developer license costs 99$/year (wtf?!)

However all protocols and interfaces are well documented so it shouldn't be impossible for an outsider to get started on an app. If someone wants to build an app for iOS I am happy to answer the one or the other question.

For now: Android devices can be very cheap. I am testing everything on my two year old OnePlus X. Future phones (even the cheap ones) should not have any problems running the app.
