### ISSUE TITLE
Feature request: Add support for ESP32 long range mode

### ISSUE THREAD

**Issue by drtrigon** [seeul8er/DroneBridge#88]
ESP32 supports a long-range mode with ~1km line of sight range. This mode was introduced quite a while ago.

Please include an option to enable this mode when using ESP32.

More information can be found here: https://www.hackster.io/news/long-range-wifi-for-the-esp32-9429ab89f450

**Comment by seeul8er** [comment]
ESP32 lacks an appropriate high-speed interface for a video stream.

**Comment by drtrigon** [comment]
@seeul8er: What is the relation between long-range mode and "high-speed interface for video stream" ? I would like to use DroneBridge for Telemetry with ArduPilot. That does not need to be high-speed. As I understand from the linked page it should be fairly easy to enable the long-range mode and thus I consider it as useful.
