### ISSUE TITLE
Drone Bridge web interface crashes after saving updated settings. ESP32-C3 Xiao Seeed Studio.

### ISSUE THREAD

**Issue by OmegaphysX7** [seeul8er/DroneBridge#94]
![image](https://github.com/DroneBridge/DroneBridge/assets/160492874/fcf55159-d7cc-4420-be05-e6c1e36f3df7)
After updating the settings/parameters the webpage fails to open again. SSID shows up in the wifi networks though,  and accepts pings through terminal/cmd
Also, Mission planner is unable to connect to its FC via DronebridgeESP32 WiFi

Tried flashing the wifi module with binaries of both Releases v1.4 & v1.3 of DroneBridge/ESP32, both present the same problem.
Flashing was done through ESP_IDF V5.1 via powershell.

**Comment by seeul8er** [comment]
Duplicate: https://github.com/DroneBridge/ESP32/issues/61
I ordered the module, will find a fix once it arrived
